### ISSUE TITLE
Bluetooth music streaming soft reboot

### ISSUE THREAD

**Issue by JustArchi** [ArchiDroid/android_device_samsung_i9300#82]
I need to check if it's actually not caused by my optimizations in AD.

```
I/Process (24511): Sending signal. PID: 25162 SIG: 3
I/art     (25162): Thread[5,tid=25179,WaitingInMainSignalCatcherLoop,Thread*=0x425f6c00,peer=0x12c000a0,"Signal Catcher"]: reacting to signal 3
I/art     (24511): Wrote stack traces to '/data/anr/traces.txt'
D/bt-btif (25610): ## register_notification_rsp ## event_id:AVRC_EVT_PLAY_POS_CHANGED
D/bt-btif (25610): LCB lcb=1 event=2 state=2
D/bt-btif (25610): LCB lcb=1 event=6 state=2
D/bt-btif (25610): bta_av_rc_msg_cback handle: 0 opcode=0x0
D/bt-btif (25610):  bta_av_rc_msg bta_av_rc_msg opcode: 0
D/bt-btif (25610): btif_av_state_started_handler event:BTA_AV_META_MSG_EVT flags 0
D/bt-btif (25610): btif_rc_handler event:BTA_AV_META_MSG_EVT
D/bt-btif (25610): AVRC_ParsCommand() return status:0x4a066438
D/bt-btif (25610): btif_rc_upstreams_evt pdu: AVRC_PDU_REGISTER_NOTIFICATION handle: 0x0 ctype:3 label:7
D/bt-btif (25610): ## register_notification_rsp ## event_id:AVRC_EVT_PLAY_POS_CHANGED
D/bt-btif (25610): LCB lcb=1 event=2 state=2
I/art     (25162): Wrote stack traces to '/data/anr/traces.txt'
D/bt-btif (25610): ## register_notification_rsp ## event_id:AVRC_EVT_PLAY_POS_CHANGED
D/bt-btif (25610): LCB lcb=1 event=2 state=2
D/bt-btif (25610): LCB lcb=1 event=6 state=2
D/bt-btif (25610): bta_av_rc_msg_cback handle: 0 opcode=0x0
D/bt-btif (25610):  bta_av_rc_msg bta_av_rc_msg opcode: 0
D/bt-btif (25610): btif_av_state_started_handler event:BTA_AV_META_MSG_EVT flags 0
D/bt-btif (25610): btif_rc_handler event:BTA_AV_META_MSG_EVT
D/bt-btif (25610): AVRC_ParsCommand() return status:0x4a066438
D/bt-btif (25610): btif_rc_upstreams_evt pdu: AVRC_PDU_REGISTER_NOTIFICATION handle: 0x0 ctype:3 label:8
D/bt-btif (25610): ## register_notification_rsp ## event_id:AVRC_EVT_PLAY_POS_CHANGED
D/bt-btif (25610): LCB lcb=1 event=2 state=2
D/bt-btif (25610): ## register_notification_rsp ## event_id:AVRC_EVT_PLAY_POS_CHANGED
D/bt-btif (25610): LCB lcb=1 event=2 state=2
D/bt-btif (25610): LCB lcb=1 event=6 state=2
D/bt-btif (25610): bta_av_rc_msg_cback handle: 0 opcode=0x0
D/bt-btif (25610):  bta_av_rc_msg bta_av_rc_msg opcode: 0
D/bt-btif (25610): btif_av_state_started_handler event:BTA_AV_META_MSG_EVT flags 0
D/bt-btif (25610): btif_rc_handler event:BTA_AV_META_MSG_EVT
D/bt-btif (25610): AVRC_ParsCommand() return status:0x4a066438
D/bt-btif (25610): btif_rc_upstreams_evt pdu: AVRC_PDU_REGISTER_NOTIFICATION handle: 0x0 ctype:3 label:9
D/bt-btif (25610): ## register_notification_rsp ## event_id:AVRC_EVT_PLAY_POS_CHANGED
D/bt-btif (25610): LCB lcb=1 event=2 state=2
I/Watchdog_N(24511): dumpKernelStacks
I/Process (24511): Sending signal. PID: 24511 SIG: 9
W/Watchdog(24511): *** WATCHDOG KILLING SYSTEM PROCESS: Blocked in handler on main thread (main)
W/Watchdog(24511): main thread stack trace:
W/Watchdog(24511):     at android.media.AudioSystem.setParameters(Native Method)
W/Watchdog(24511):     at android.media.AudioService$AudioServiceBroadcastReceiver.onReceive(AudioService.java:5243)
W/Watchdog(24511):     at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:867)
W/Watchdog(24511):     at android.os.Handler.handleCallback(Handler.java:739)
W/Watchdog(24511):     at android.os.Handler.dispatchMessage(Handler.java:95)
W/Watchdog(24511):     at android.os.Looper.loop(Looper.java:135)
W/Watchdog(24511):     at com.android.server.SystemServer.run(SystemServer.java:298)
W/Watchdog(24511):     at com.android.server.SystemServer.main(SystemServer.java:186)
W/Watchdog(24511):     at java.lang.reflect.Method.invoke(Native Method)
W/Watchdog(24511):     at java.lang.reflect.Method.invoke(Method.java:372)
W/Watchdog(24511):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
W/Watchdog(24511):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/Watchdog(24511): *** GOODBYE!
E/bt-btif (25610): [media task tx timer] ts 141370098221, diff : 00032561, queue sz 0
```

**Comment by JustArchi** [comment]
Reproduced on clean CM build

**Comment by JustArchi** [comment]
Not a kernel issue - reproduced also on Boeffla kernel.

**Comment by JustArchi** [comment]
This happens only after device goes to sleep.

```
W/ActivityManager( 2757): Sleep timeout!  Sleeping now.
W/ActivityManager( 2757): Activity stop timeout for ActivityRecord{2e0900b5 u0 com.cyanogenmod.eleven/.ui.activities.HomeActivity t62}
W/BroadcastQueue( 2757): Timeout of broadcast BroadcastRecord{4a31868 u-1 android.intent.action.SCREEN_OFF} - receiver=android.app.LoadedApk$ReceiverDispatcher$InnerReceiver@ab40228, started 10000ms ago
W/BroadcastQueue( 2757): Receiver during timeout: BroadcastFilter{2e4d08e6 u0 ReceiverList{3a3d4b41 2757 system/1000/u0 local:ab40228}}
W/BroadcastQueue( 2757): Timeout of broadcast BroadcastRecord{4a31868 u-1 android.intent.action.SCREEN_OFF} - receiver=android.app.LoadedApk$ReceiverDispatcher$InnerReceiver@1fb0aa7b, started 10001ms ago
W/BroadcastQueue( 2757): Receiver during timeout: BroadcastFilter{31b600f1 u0 ReceiverList{284c4098 2757 system/1000/u0 local:1fb0aa7b}}
W/BroadcastQueue( 2757): Timeout of broadcast BroadcastRecord{4a31868 u-1 android.intent.action.SCREEN_OFF} - receiver=android.app.LoadedApk$ReceiverDispatcher$InnerReceiver@2ba6ee83, started 10003ms ago
W/BroadcastQueue( 2757): Receiver during timeout: BroadcastFilter{1bb4b839 u0 ReceiverList{2f11a800 2757 system/1000/u0 local:2ba6ee83}}
W/BroadcastQueue( 2757): Timeout of broadcast BroadcastRecord{4a31868 u-1 android.intent.action.SCREEN_OFF} - receiver=android.app.LoadedApk$ReceiverDispatcher$InnerReceiver@1f60292a, started 10005ms ago
W/BroadcastQueue( 2757): Receiver during timeout: BroadcastFilter{2ba43cb8 u0 ReceiverList{28f8831b 2757 system/1000/u0 local:1f60292a}}
W/BroadcastQueue( 2757): Timeout of broadcast BroadcastRecord{4a31868 u-1 android.intent.action.SCREEN_OFF} - receiver=android.app.LoadedApk$ReceiverDispatcher$InnerReceiver@12440ef3, started 10003ms ago
W/BroadcastQueue( 2757): Receiver during timeout: BroadcastFilter{1e8a6629 u0 ReceiverList{67a97b0 2757 system/1000/u0 local:12440ef3}}
I/Process ( 2757): Sending signal. PID: 2757 SIG: 3
I/art     ( 2757): Thread[5,tid=2766,WaitingInMainSignalCatcherLoop,Thread*=0x42428c00,peer=0x12c020a0,"Signal Catcher"]: reacting to signal 3
E/WifiHAL ( 2757): Error polling socket
I/art     ( 2757): Wrote stack traces to '/data/anr/traces.txt'
W/BroadcastQueue( 2757): Timeout of broadcast BroadcastRecord{4a31868 u-1 android.intent.action.SCREEN_OFF} - receiver=android.app.LoadedApk$ReceiverDispatcher$InnerReceiver@c2a7733, started 10006ms ago
W/BroadcastQueue( 2757): Receiver during timeout: BroadcastFilter{3141a869 u0 ReceiverList{2d87af0 2757 system/1000/u0 local:c2a7733}}
W/BroadcastQueue( 2757): Timeout of broadcast BroadcastRecord{193fa926 u0 android.net.ConnectivityService.action.PKT_CNT_SAMPLE_INTERVAL_ELAPSED} - receiver=android.app.LoadedApk$ReceiverDispatcher$InnerReceiver@38c7791c, started 60006ms ago
W/BroadcastQueue( 2757): Receiver during timeout: BroadcastFilter{383f9afa u0 ReceiverList{3b7d4925 2757 system/1000/u0 local:38c7791c}}
I/Process ( 2757): Sending signal. PID: 2757 SIG: 3
I/art     ( 2757): Thread[5,tid=2766,WaitingInMainSignalCatcherLoop,Thread*=0x42428c00,peer=0x12c020a0,"Signal Catcher"]: reacting to signal 3
E/WifiHAL ( 2757): Error polling socket
I/Process ( 2757): Sending signal. PID: 3393 SIG: 3
I/art     ( 3393): Thread[5,tid=3415,WaitingInMainSignalCatcherLoop,Thread*=0x425f2800,peer=0x12c000a0,"Signal Catcher"]: reacting to signal 3
I/art     ( 2757): Wrote stack traces to '/data/anr/traces.txt'
I/art     ( 3393): Wrote stack traces to '/data/anr/traces.txt'
I/Watchdog_N( 2757): dumpKernelStacks
W/Watchdog( 2757): *** WATCHDOG KILLING SYSTEM PROCESS: Blocked in handler on main thread (main)
W/Watchdog( 2757): main thread stack trace:
W/Watchdog( 2757):     at android.media.AudioSystem.setParameters(Native Method)
W/Watchdog( 2757):     at android.media.AudioService$AudioServiceBroadcastReceiver.onReceive(AudioService.java:5243)
W/Watchdog( 2757):     at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:867)
W/Watchdog( 2757):     at android.os.Handler.handleCallback(Handler.java:739)
W/Watchdog( 2757):     at android.os.Handler.dispatchMessage(Handler.java:95)
W/Watchdog( 2757):     at android.os.Looper.loop(Looper.java:135)
I/Process ( 2757): Sending signal. PID: 2757 SIG: 9
W/Watchdog( 2757):     at com.android.server.SystemServer.run(SystemServer.java:298)
W/Watchdog( 2757):     at com.android.server.SystemServer.main(SystemServer.java:186)
W/Watchdog( 2757):     at java.lang.reflect.Method.invoke(Native Method)
W/Watchdog( 2757):     at java.lang.reflect.Method.invoke(Method.java:372)
W/Watchdog( 2757):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
W/Watchdog( 2757):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
W/Watchdog( 2757): *** GOODBYE!
```

**Comment by JustArchi** [comment]
Not nice, it looks like pegasusq's aggresive hotplug/clock-down results in lack of CPU power enough to handle all events, Android reacts to it as it would be a deadlock (it is, technically), and reboots system_server.

Performance governor seems to solve this issue, but it's not acceptable solution.

I'll need to find out what is the exact problem and tune pegasusq defaults accordingly.

**Comment by JustArchi** [comment]
Confirmed: This issue happens only if only CPU0 is available (frequency doesn't matter).

After turning on the second core, issue is gone.

So this issue is most likely caused by the kernel (turning off interrupts, even when they're needed, because of CONFIG_NO_HZ).

**Comment by JustArchi** [comment]
Something is wrong with Android, this issue can also randomly not happen while only at one core. It doesn't seem to be device-related for me now.

**Comment by JustArchi** [comment]
Confirmed also with smdk4412 kernel.
```
W/BroadcastQueue( 2581): Timeout of broadcast BroadcastRecord{3294a45e u-1 android.intent.action.SCREEN_ON} - receiver=android.app.LoadedApk$ReceiverDispatcher$InnerReceiver@18cb24a8, started 10000ms ago
W/BroadcastQueue( 2581): Receiver during timeout: BroadcastFilter{358b2f66 u0 ReceiverList{3599fbc1 2581 system/1000/u0 local:18cb24a8}}
```
